src/Entity/Info.php
<?php

namespace App\Entity;

use App\Repository\InfoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InfoRepository::class)]
class Info
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $modifiedAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $publicationAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?bool $public = null;

    #[ORM\ManyToOne(inversedBy: 'info')]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Localisation = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $EventAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $cratedAt): self
    {
        $this->createdAt = $cratedAt;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modifiedAt;
    }

    public function setModifiedAt(?\DateTimeImmutable $modifiedAt): self
    {
        $this->modifiedAt = $modifiedAt;

        return $this;
    }

    public function getPublicationAt(): ?\DateTimeImmutable
    {
        return $this->publicationAt;
    }

    public function setPublicationAt(?\DateTimeImmutable $publicationAt): self
    {
        $this->publicationAt = $publicationAt;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLocalisation(): ?string
    {
        return $this->Localisation;
    }

    public function setLocalisation(?string $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    public function getEventAt(): ?\DateTimeImmutable
    {
        return $this->EventAt;
    }

    public function setEventAt(?\DateTimeImmutable $EventAt): self
    {
        $this->EventAt = $EventAt;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Repository\InfoRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class FrontController extends AbstractController
{
    #[Route('/', name: 'homepage')]
    public function index(): Response
    {
        return $this->render('front/index.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/association', name: 'app_front_association')]
    public function association(): Response
    {
        return $this->render('front/pages/association.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses', name: 'app_front_danses')]
    public function danses(): Response
    {
        return $this->render('front/pages/danses.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/rock', name: 'app_front_rock')]
    public function rock(): Response
    {
        return $this->render('front/pages/dansesRock.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/chacha', name: 'app_front_chacha')]
    public function chacha(): Response
    {
        return $this->render('front/pages/dansesChacha.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/salsa', name: 'app_front_salsa')]
    public function salsa(): Response
    {
        return $this->render('front/pages/dansesSalsa.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/rumba', name: 'app_front_rumba')]
    public function rumba(): Response
    {
        return $this->render('front/pages/dansesRumba.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/paso', name: 'app_front_paso')]
    public function paso(): Response
    {
        return $this->render('front/pages/dansesPaso.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/danses/groupe', name: 'app_front_groupe')]
    public function groupe(): Response
    {
        return $this->render('front/pages/dansesGroupe.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/evenements', name: 'app_front_evenements')]
    public function evenements(InfoRepository $infoRepository): Response
    {
        //liste des infos publiques
        return $this->render('front/pages/evenements.html.twig', [
            'controller_name' => 'FrontController',
            'infosPublic' => $infoRepository->findBy(
                array('public'=> '1'),
                array('createdAt' => 'DESC'),
                10,
                0
            )
        ]);
    }

    #[Route('/inscription', name: 'app_front_inscription')]
    public function inscription(): Response
    {
        return $this->render('front/pages/inscription.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/contact', name: 'app_front_contact')]
    public function contact(): Response
    {
        return $this->render('front/pages/contact.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    #[Route('/mentionsLegales', name: 'app_front_mentionsLegales')]
    public function mentionsLegales(): Response
    {
        return $this->render('front/pages/mentionsLegales.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }


}

templates/front/pages/association.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia 8 Dancing / Association{% endblock %}

{% block body %}
<div class="contentAssociation">
    <h2>L'association : Virevolte </h2>
    <div class="imgAssociation">
        <img src="{{ asset('./media/couples_pixabay_AMDUMA_1920.jpg') }}" alt="images de danseurs en duo">
    </div>
    <div class="presentationAssociation">
        <p>L’association, créée en juillet 2011 par des amateurs de danse de différents niveaux souhaitant
            progresser dans cette activité, propose aujourd’hui des ateliers de toutes danses tous les jeudis à
            Forcalquier.</p>
        <p>L’association a commencé par l’objectif de développer la danse de salon et la danse en ligne en
            proposant un apprentissage afin d’être à l’aise et de prendre plaisir en dansant selon les
            opportunités (bals, dancings, fêtes locales ou familiales, mariages, etc.) et cela aussi bien en
            danse à deux qu’en danse individuelle.</p>
    </div>
    <div class="presentationAdhérent">
        <p>Une majorité de nos adhérents cumule danse de salon et danse en ligne. La danse en ligne ne
            nécessitant pas de partenaire est donc un avantage pour les personnes seules qui souhaitent se
            divertir sur de la musique. On peut donc répéter les chorégraphies à la maison, sortir en
            soirée.</p>
    </div>
</div>
{% endblock %}

templates/front/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia 8 Dancing / Contact{% endblock %}

{% block body %}
        <section class="sectionContact">
            <h2>Contact</h2>
            <div class="contact">
                <iframe class="carte"
                    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11487.586065677011!2d5.7779654!3d43.9615063!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5a637e2de68e2af5!2sEcole%20L%C3%A9on%20Espariat!5e0!3m2!1sfr!2sfr!4v1654250204938!5m2!1sfr!2sfr"
                    width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
                <h4>Aurélia 8 dancing & Virevolte</h4>
                <div class="adresse">
                    <i class="icon-map"></i>
                    <p>Salle Léon Espériat Forcaliquier</p>
                </div>
                <div class="tel">
                    <i class="icon-phone"></i>
                    <div class="telProf">
                        <p> Professeur </p>
                        <p> 06.XX.XX.XX.XX </p>
                        <p> <a href="tel:+625565645">Cliquer pour m'apperler</a> </p>
                    </div>
                    <div class="telPresident">
                        <p> Présidente de l'association </p>
                        <p> 06.XX.XX.XX.XX </p>
                        <p> <a href="tel:+625565646">Cliquer pour m'apperler</a> </p>
                    </div>
                </div>
            </div>
            <form action="contact.php" method="post" class="formContact">
                <fieldset>
                    <legend>Envoyer un message</legend>
                    <div class="row">
                        <label class="legend" for="contact_name">Nom</label>
                        <input class="champsSaisie" type="text" name="contact_name" placeholder="saisir votre nom"
                            required />
                    </div>
                    <div class="row">
                        <label class="legend" for="contact_mail">Email</label>
                        <input class="champsSaisie" type="email" name="contact_mail" placeholder="saisir votre Email"
                            required />
                    </div>
                    <div class="row">
                        <label class="legend" for="contact_sujet">Objet</label>
                        <input class="champsSaisie" type="text" name="contact_sujet" placeholder="saisir l'objet de votre message" />
                    </div>
                    <div class="row">
                        <label class="legend" for="contact_content">Message</label>
                        <textarea class="message" cols="40" rows="15" name="contact_content"
                            placeholder="saisir votre message..." required></textarea>
                    </div>
                    <div class="row">
                        <button class="buttonSubmit" type="submit" value="submit" name="envoi">Envoyer</button>
                        <button type="reset" class="buttonReset" value="reset">Annuler</button>
                    </div>
                </fieldset>
            </form>
        </section>
{% endblock %}

templates/front/pages/danses.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia 8 Dancing / Danses{% endblock %}

{% block body %}
<div class="danses">
    <div class="rockDanse">
        <a href="{{ path('app_front_rock') }}">
            <h4>Rock'n Roll</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-1.png') }}" alt="danse en rock">
        </a>
    </div>
    <div class="chachaDanse">
        <a href="{{ path('app_front_chacha') }}">
            <h4>Chacha</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-3.png') }}" alt="danse en chacha">
        </a>
    </div>
    <div class="salsaDanse">
        <a href="{{ path('app_front_salsa') }}">
            <h4>Salsa</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-11.png') }}" alt="danse en salsa">
        </a>
    </div>
    <div class="rumbaDanse">
        <a href="{{ path('app_front_rumba') }}">
            <h4>Rumba</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en rumba">
        </a>
    </div>
    <div class="pasoDanse">
        <a href="{{ path('app_front_paso') }}">
            <h4>Paso Doble</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-13.png') }}" alt="danse en paso">
        </a>
    </div>
    <div class="groupeDanse">
        <a href="{{ path('app_front_groupe') }}">
            <h4>Groupe</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en groupe">
        </a>
    </div>
</div>
<div class="contentDanses">
    <h2>Les differents types de danses</h2>
    <div class="imgDansesDuo">
        <img src="{{ asset('./media/argentinian-tango_pixabay_Bernard-Verougstraete.jpg') }}"
            alt="images de danseurs en duo">
    </div>
    <div class="dansesDuoPresentation">
        <h3>La danse de salon </h3>
        <p> La danse de salon appelée aussi danse de loisirs regroupe différentes danses que l’on retrouve au bal :
            <ul>
                <li>Les danses dites « latines » : rock, cha-cha, rumba, bachata, salsa et samba.</li>
                <li>Les danses dites « standards » : tango, paso-doble, quick step, valse viennoise, valse lente.</li>
            </ul>
    </div>
    <div class="dansesGroupePrésentation">
        <h3>La danse en groupe </h3>
        <p> Le madison et la country sont en général bien identifiés par le public, mais la danse en en groupe ou line dance, est assez peu connue.
            <ul>
                <li>La danse en ligne est un enchaînement de pas, divisé en plusieurs sections de huit contes, écrits pour coller à la musique.</li>
                <li> Notre objectif étant de s’amuser dans les soirées dansantes, nous choisissons comme support musical des rythmes variés comme le rock, le cha-cha, le merengue, la
            rumba, la variété française et internationale. </li>
            </ul>       
    </div>
    <div class="imgDansesGroupe">
        <img src="{{ asset('./media/zumba_pixabay_Andrzej_Rembowski.jpg') }}" alt="images de danseurs en duo">
    </div>
</div>
{% endblock %}

templates/front/pages/dansesChacha.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia8Dancing/Chacha{% endblock %}

{% block javascripts %}
            {{ encore_entry_script_tags('app') }}
{% endblock %}

{% block body %}
<div class="danses">
    <div class="rockDanse">
        <a href="{{ path('app_front_rock') }}">
            <h4>Rock'n Roll</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-1.png') }}" alt="danse en rock">
        </a>
    </div>
    <div class="chachaDanse">
        <a href="{{ path('app_front_chacha') }}">
            <h4>Chacha</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-3.png') }}" alt="danse en chacha">
        </a>
    </div>
    <div class="salsaDanse">
        <a href="{{ path('app_front_salsa') }}">
            <h4>Salsa</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-11.png') }}" alt="danse en salsa">
        </a>
    </div>
    <div class="rumbaDanse">
        <a href="{{ path('app_front_rumba') }}">
            <h4>Rumba</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en rumba">
        </a>
    </div>
    <div class="pasoDanse">
        <a href="{{ path('app_front_paso') }}">
            <h4>Paso Doble</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-13.png') }}" alt="danse en paso">
        </a>
    </div>
    <div class="groupeDanse">
        <a href="{{ path('app_front_groupe') }}">
            <h4>Groupe</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en groupe">
        </a>
    </div>
</div>
<div class="danse contentChacha">
    <h2>Chacha</h2>
    <div class="dansesHistoire translationLeft">
        <p>Chacha Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias dolore, officia ab ullam aut a unde deleniti? Asperiores tempore ipsa ullam nostrum neque aspernatur necessitatibus doloremque eligendi, cumque quibusdam sint dolore nesciunt quos iusto tempora voluptate, dolores, ad illo quaerat excepturi. Necessitatibus laborum eos voluptatum soluta, magnam quia repellat quasi!
        </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias dolore, officia ab ullam aut a unde deleniti? Asperiores tempore ipsa ullam nostrum neque aspernatur necessitatibus doloremque eligendi, cumque quibusdam sint dolore nesciunt quos iusto tempora voluptate, dolores, ad illo quaerat excepturi. Necessitatibus laborum eos voluptatum soluta, magnam quia repellat quasi!
        </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias dolore, officia ab ullam aut a unde deleniti? Asperiores tempore ipsa ullam nostrum neque aspernatur necessitatibus doloremque eligendi, cumque quibusdam sint dolore nesciunt quos iusto tempora voluptate, dolores, ad illo quaerat excepturi. Necessitatibus laborum eos voluptatum soluta, magnam quia repellat quasi!
        </p>
    </div>
    <div class="dansesPasBaseMenu ">
        <button class="buttonPasBase buttonPasBaseHistoire" type="button" name="Histoire">Histoire de la danse</button>
        <button class="buttonPasBase buttonPasBase1" type="button" name="pasBase1">Pas de Base 1</button>
        <button class="buttonPasBase buttonPasBase2" type="button" name="pasBase2">Pas de Base 2</button>
        <button class="buttonPasBase buttonPasBase3" type="button" name="pasBase3">Pas de Base 3</button>
        <button class="buttonPasBase buttonPasBase4" type="button" name="pasBase4">Pas de Base 4</button>
    </div>
    <div class="hidden dansesPasBase dansesPasBase1">
        <div class="descriptionPasbase">
            <p>Pas de base 1 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos non dolor voluptate accusamus voluptates iure mollitia sapiente omnis, corporis quis perspiciatis impedit, provident quam ratione cum error nihil consequuntur. Quibusdam explicabo aliquid veritatis delectus. Aspernatur at, incidunt a suscipit aliquam alias vitae adipisci, magnam iusto corrupti, hic consectetur quidem debitis?</p>
        </div>
        <div class="videoPasBase">
            <video controls src="{{ asset('./media/danses/Rock en comptes 2.mp4') }}"></video>
        </div>
    </div>
    <div class="hidden dansesPasBase dansesPasBase2">
        <div class="descriptionPasbase">
            <p>Pas de base 2 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos non dolor voluptate accusamus voluptates iure mollitia sapiente omnis, corporis quis perspiciatis impedit, provident quam ratione cum error nihil consequuntur. Quibusdam explicabo aliquid veritatis delectus. Aspernatur at, incidunt a suscipit aliquam alias vitae adipisci, magnam iusto corrupti, hic consectetur quidem debitis?</p>
        </div>
        <div class="videoPasBase">
            <video controls src="{{ asset('./media/danses/Rock en comptes 2.mp4') }}"></video>
        </div>
    </div>
    <div class="hidden dansesPasBase dansesPasBase3 ">
        <div class="descriptionPasbase">
            <p>Pas de base 3 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos non dolor voluptate accusamus voluptates iure mollitia sapiente omnis, corporis quis perspiciatis impedit, provident quam ratione cum error nihil consequuntur. Quibusdam explicabo aliquid veritatis delectus. Aspernatur at, incidunt a suscipit aliquam alias vitae adipisci, magnam iusto corrupti, hic consectetur quidem debitis?</p>
        </div>
        <div class="videoPasBase">
            <video controls src="{{ asset('./media/danses/Honky Tonk Twist explications.mp4') }}"></video>
        </div>
    </div>
    <div class="hidden dansesPasBase dansesPasBase4 ">
        <div class="descriptionPasbase">
            <p>Pas de base 4 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quos non dolor voluptate accusamus voluptates iure mollitia sapiente omnis, corporis quis perspiciatis impedit, provident quam ratione cum error nihil consequuntur. Quibusdam explicabo aliquid veritatis delectus. Aspernatur at, incidunt a suscipit aliquam alias vitae adipisci, magnam iusto corrupti, hic consectetur quidem debitis?</p>
        </div>
        <div class="videoPasBase">
            <video controls src="{{ asset('./media/danses/All about that bass explications.mp4') }}"></video>
        </div>
    </div>
</div>
{% endblock %}

templates/front/pages/dansesGroupe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia8Dancing/Groupe{% endblock %}

{% block body %}
<div class="danses">
    <div class="rockDanse">
        <a href="{{ path('app_front_rock') }}">
            <h4>Rock'n Roll</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-1.png') }}" alt="danse en rock">
        </a>
    </div>
    <div class="chachaDanse">
        <a href="{{ path('app_front_chacha') }}">
            <h4>Chacha</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-3.png') }}" alt="danse en chacha">
        </a>
    </div>
    <div class="salsaDanse">
        <a href="{{ path('app_front_salsa') }}">
            <h4>Salsa</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-11.png') }}" alt="danse en salsa">
        </a>
    </div>
    <div class="rumbaDanse">
        <a href="{{ path('app_front_rumba') }}">
            <h4>Rumba</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en rumba">
        </a>
    </div>
    <div class="pasoDanse">
        <a href="{{ path('app_front_paso') }}">
            <h4>Paso Doble</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-13.png') }}" alt="danse en paso">
        </a>
    </div>
    <div class="groupeDanse">
        <a href="{{ path('app_front_groupe') }}">
            <h4>Groupe</h4>
            <img src="{{ asset('../media/happy-dancing-people-icons-7.png') }}" alt="danse en groupe">
        </a>
    </div>
</div>
<div class="danse contentGroupe hidden">
    <h2>Groupe</h2>
    <div class="dansesHistoire dansesHistoireGroupe hidden">
        <p>La catégorie des danses en groupe (dites "danses en ligne") comprend toutes les danses de groupes pratiquées individuellement, soit l'un derrière l'autre, soit côte à côte, soit encore en deux lignes se faisant face. On trouve des danses en groupe tant parmi les danses traditionnelles que parmi les danses de société ou les danses rock.<p>
        <p>Parmi les exemples de danse en groupe les plus connus, on trouve le madison des années 1960, les danses country appartiennent également à ce style et plus récent la macarena ou le kuduro.
        <p>La danse en groupe est une pratique qui consiste à danser sur des rythmes de rock, rumba, charleston, mambo, valse, tango, slow, cha-cha-cha, reggae, foxtrot, disco, samba, sur des chorégraphies précises, en ligne et sans partenaire.</p>
        <p>Au départ, cette disposition en ligne permettait d'apprendre plus facilement les danses. Ces danses permettent de maintenir une meilleure distanciation physique que les danses en contact. </p>
    </div>
    <div class="dansesPasBaseMenu ">
        <button class="buttonPasBase buttonPasBaseHistoire" type="button" name="Histoire">Histoire de la danse</button>
        <button class="buttonPasBase buttonPasBase1" type="button" name="pasBase1">Pas de Base </button>
    </div>
    <div class="hidden dansesPasBase dansesPasBase1">
        <div class="descriptionPasbase">
            <p> Abréviations: D = Pied DROIT - G = Pied GAUCHE - PC = Poids du Corps</p>
            <table class="pasDeBaseGroupe">
                <thead>         
                    <tr>
                        <th>Mouvement</th>
                        <th>Description</th>
                    </tr>
                </thead>         
                <tbody>         
                    <tr>
                        <td class="mouvement">ACROSS</td>
                        <td>
                            <ul>
                                <li>Mouvement qui traverse la piste de danse.</li>
                                <li>Avancer le pied en croisant devant l'autre pied.</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td class="mouvement">BRUSH</td>
                        <td>
                            <ul>
                                <li>1 MOUVEMENT = 1 TEMPS</li>
                                <li>Brosser le sol avec la plante (= ball) du pied.</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td class="mouvement">BUMP ou HIP BUMP= BALANCEMENT DES HANCHES</td>
                        <td>
                            <ul>
                                <li>1 MOUVEMENT = 1 TEMPS</li>
                                <li>Coup de hanche à droite (avec PC sur D) ou à gauche (avec PC sur G). Le BUMP peut être fait dans les diagonales.</li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td class="mouvement">CLAP</td>
                        <td>
                            <ul>
                                <li>1 MOUVEMENT = 1 TEMPS.</li>
                                <li>Taper des mains.</li>
                            </ul>
                        </td>
                    </tr>
                </tbody> 
        </div>
    </div>
</div>
{% endblock %}

templates/front/pages/evenements.html.twig
{% extends 'base.html.twig' %}

{% block title %}Aurélia 8 Dancing / Evénements{% endblock %}

{% block body %}
<section class="contentEvent">
    <h2>Evenements </h2>
    <div class="row">
        {% for info in infosPublic %}
        <div class="event">
            <div class="affiche">
                <img src="{{ asset('uploads/pictureInfo/' ~info.picture) }}" alt="image de {{ info.title }}" class="img-fluid rounded-start" >
                <legend>créée le {{ info.createdAt ? info.createdAt|date('d-m-Y H:i') : '' }}</small></legend>
            </div>
            <div class="afficheText">
                    <h3>{{ info.title }}</h3>
                    <h5>Le {{ info.eventAt ? info.eventAt|date('d-m-Y H:i') : '' }}</h5>
                    <h6>à {{ info.localisation }}</h6>
                    <p>{{ info.content }}</p>
            </div>
        </div>
        {% else %}
        <tr>
            <td colspan="10">no records found</td>
        </tr>
        {% endfor %}
    </div>
</section>
{% endblock %}